REGEN: projects

diff --git a/projects/idebuild b/projects/idebuild
--- a/projects/idebuild
+++ b/projects/idebuild
@@ -4,9 +4,21 @@
 #
 
 PRODUCT=goahead
-VS="${PROGRAMFILES}/Microsoft Visual Studio 10.0/Common7/IDE/devenv.exe"
 XCODE=/usr/bin/xcodebuild
 PROFILE=default
+BINARIES="goahead gohead-test gopass"
+LIBRARIES="libgo"
+
+# Just for VS
+unset TEMP TMP
+
+for v in 12 11 10
+do
+    VS="/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/devenv.exe"
+    if [ -x "${VS}" ] ; then
+        break
+    fi
+done
 
 log() {
     tag=$1
@@ -18,6 +30,23 @@ if [ -x "${VS}" ] ; then
     log "[Test]" "Building ${PRODUCT} Visual Studio Project"
     "${VS}" projects/${PRODUCT}-windows-${PROFILE}.sln /clean
     "${VS}" projects/${PRODUCT}-windows-${PROFILE}.sln /build
+
+    for f in $BINARIES
+    do
+        echo check $f
+        if [ ! -f projects/${PRODUCT}-x86-default/bin/${f}.exe ] ; then
+            echo "VS IDE build is missing $f.exe"
+            exit 255
+        fi
+    done
+    for f in $LIBRARIES
+    do
+        echo check $f
+        if [ ! -f projects/${PRODUCT}-x86-default/bin/${f}.dll ] ; then
+            echo "VS IDE build is missing $f.dll"
+            exit 255
+        fi
+    done
 fi
 
 if [ -x "${XCODE}" ] ; then
