Update for stand-alone bit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,17 +2,21 @@
 #
 #   configure -- Configure for building
 #
-MIN_BIT=2.0.1
+#   Configure will invoke bit configure to prepare for building. If bit is not installed,
+#   configuration is not required. Variables can be passed to make to modify the build.
+#
+NAME=goahead
+OS=`uname | sed 's/CYGWIN.*/windows/;s/Darwin/macosx/' | tr '[A-Z]' '[a-z]'`
+PROFILE=debug
+EXT=mk
+MIN_BIT=0.8.0
 
 if ! type bit >/dev/null 2>&1 ; then
-    echo "" >&2
-    echo "Install the \"bit\" tool from Ejscript $MIN_BIT or later for configuring." >&2
-    echo "Distributed as part of Ejscript:" >&2
-    echo "  http://ejscript.org/downloads/ejs/download.ejs" >&2
-    echo "" >&2
-    echo "Or skip configuring and make a standard build using \"make\"." >&2
-    echo "" >&2
-    exit 255
+    echo '' >&2
+    echo "To configure ${NAME}, the \"bit\" tool is required. You can continue with a" >&2
+    echo 'default build by using make.' >&2
+    make help
+    exit 0
 fi
 
 ver=`(echo $MIN_BIT ; bit -V) | sort -r | head -n 1`
@@ -20,4 +24,7 @@ if [ "${MIN_BIT}" = "${ver}" ] ; then
     echo Please upgrade \"bit\" to $MIN_BIT
     exit 255
 fi
-bit configure $*
+if [ -f start.bit ] ; then
+    bit clean >/dev/null 2>&1
+fi
+bit configure "$@"
